name: deploy

on:
  push:
    branches:
      - main
      # - develop

permissions:
  id-token: write
  contents: read # actions/checkout のために必要

# env:
#  AWS_REGION: ap-northeast-1


jobs:
  get-caller-identity:
    runs-on: ubuntu-latest 
    steps:
      - name: Configure AWS credentials for prod
      #  if: github.ref == 'refs/heads/main'
        uses: actions/checkout@v2
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions
          aws-region: ap-northeast-1    # ${{ env.AWS_REGION }} 
        run: aws sts get-caller-identity 

      #- name: Configure AWS credentials for dev
      #  if: github.ref == 'refs/heads/dev'
      #- uses: actions/checkout@v2
      #- uses: aws-actions/configure-aws-credentials@v1
      #  with:
      #    role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions
      #    aws-region: ${{ env.AWS_REGIONS }} 
      #- run: aws sts get-caller-identity 