name: OIDC Test

on: push

env:
  AWS_REGIONS: ap-northeast-1

jobs:
  get-caller-identity:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read # actions/checkout のために必要
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::751312769524:oidc-provider/token.actions.githubusercontent.com
          aws-region: ${{ env.AWS_REGION }}
      - run: aws sts get-caller-identity